<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-S8958LO2" failures="1" tests="8" name="Test" time="0.105" errors="0" timestamp="2024-05-05T13:43:04 IST">
  <testcase classname="com.testng.FailedRerunAuto" name="loginbutton" time="0.01"/>
  <testcase classname="com.testng.FailedRerunAuto" name="pass" time="0.005"/>
  <testcase classname="com.testng.FailedRerunAuto" name="user" time="0.015">
    <skipped/>
  </testcase> <!-- user -->
  <testcase classname="com.testng.FailedRerunAuto" name="user" time="0.002">
    <skipped/>
  </testcase> <!-- user -->
  <testcase classname="com.testng.FailedRerunAuto" name="user" time="0.002">
    <skipped/>
  </testcase> <!-- user -->
  <testcase classname="com.testng.FailedRerunAuto" name="user" time="0.001">
    <skipped/>
  </testcase> <!-- user -->
  <testcase classname="com.testng.FailedRerunAuto" name="user" time="0.004">
    <skipped/>
  </testcase> <!-- user -->
  <testcase classname="com.testng.FailedRerunAuto" name="user" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [Aiit] but found [Aiite]">
      <![CDATA[java.lang.AssertionError: expected [Aiit] but found [Aiite]
at com.testng.FailedRerunAuto.user(FailedRerunAuto.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- user -->
</testsuite> <!-- Test -->
