<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="LAPTOP-S8958LO2" failures="1" tests="6" name="Test(failed)" time="0.086" errors="0" timestamp="2024-05-05T12:21:27 IST">
  <testcase classname="com.testng.FailedRerun" name="user" time="0.018">
    <skipped/>
  </testcase> <!-- user -->
  <testcase classname="com.testng.FailedRerun" name="user" time="0.001">
    <skipped/>
  </testcase> <!-- user -->
  <testcase classname="com.testng.FailedRerun" name="user" time="0.001">
    <skipped/>
  </testcase> <!-- user -->
  <testcase classname="com.testng.FailedRerun" name="user" time="0.001">
    <skipped/>
  </testcase> <!-- user -->
  <testcase classname="com.testng.FailedRerun" name="user" time="0.004">
    <skipped/>
  </testcase> <!-- user -->
  <testcase classname="com.testng.FailedRerun" name="user" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [Aiit] but found [Aiite]">
      <![CDATA[java.lang.AssertionError: expected [Aiit] but found [Aiite]
at com.testng.FailedRerun.user(FailedRerun.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- user -->
  <testcase classname="com.testng.FailedRerun" name="pass" time="0.0">
    <ignored/>
  </testcase> <!-- pass -->
  <testcase classname="com.testng.FailedRerun" name="loginbutton" time="0.0">
    <ignored/>
  </testcase> <!-- loginbutton -->
</testsuite> <!-- Test(failed) -->
